datasource:
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: pass
  driver-class: org.mariadb.jdbc.Driver
  
flyway:
  user: ${datasource.username}
  password: ${datasource.password}
  schema: test
  baselineOnMigrate: true
  url: ${datasource.url}
  locations: classpath:/db/migration/common,classpath:/db/migration/mysql
